export const dataBooks = [
    {
        id: 1,
        name: "Romeo & Juliet",
        author: " William Shakespeare",
        category: "literatura",
        description: "Cuenta la historia de dos jóvenes que, a pesar de la oposición de sus familiares, rivales entre sí, deciden casarse de forma ilegal y vivir juntos; sin embargo, la presión de esa rivalidad y una serie de fatalidades conducen a que la pareja elija el suicidio antes que vivir separados.",
        image: "https://http2.mlstatic.com/D_NQ_NP_648243-MLU71296225513_082023-O.webp",
        stock: "10",
        price: "4300",
    },
    {
        id: 2,
        name: "Diario De Una Pasion",
        author: "Nicholas Sparks",
        category: "romance",
        description: "En un hogar de retiro un hombre le lee a una mujer, que sufre de Alzheimer, la historia de dos jóvenes de distintas clases sociales que se enamoraron durante la convulsionada década del 40, y de cómo fueron separados por terceros, y por la guerra.",
        image: "https://http2.mlstatic.com/D_NQ_NP_716455-MLA50890277421_072022-O.webp",
        stock: "10",
        price: "11299",
    },
    {
        id: 3,
        name: "El Resplandor",
        author: "Stephen King",
        category: "terror",
        description: "Jack Torrance acepta una oferta de trabajo en un hotel de montaña que se encuentra a 65 kilómetros del pueblo más cercano. Además, las carreteras se encuentran cerradas al tráfico por las fuertes nevadas del invierno. Pronto comenzarán a manifestarse espíritus y apariciones extrañas.",
        image: "https://http2.mlstatic.com/D_NQ_NP_679936-MLA33018282359_112019-O.webp",
        stock: "10",
        price: "7379",
    },
    {
        id: 4,
        name: "La divina comedia",
        author: " Dante Alighieri",
        category: "literatura",
        description: "Esta epopeya nos narra el un viaje espiritual que hace el propio Dante a través del Infierno, el Purgatorio y el Paraíso, de la mano del poeta Virgilio y con el objetivo de redimir sus pecados terrenales y poder ascender al Cielo.",
        image: "https://http2.mlstatic.com/D_NQ_NP_866439-MLA43738390841_102020-O.webp",
        stock: "10",
        price: "14800",
    },
    {
        id: 5,
        name: "It",
        author: "Stephen King",
        category: "terror",
        description: "Tras veintisiete años de tranquilidad y lejanía una antigua promesa infantil les hace volver al lugar en el que vivieron su infancia y juventud como una terrible pesadilla. Regresan a Derry para enfrentarse con su pasado y enterrar definitivamente la amenaza que los amargó durante su niñez. Saben que pueden morir, pero son conscientes de que no conocerán la paz hasta que aquella cosa sea destruida para siempre",
        image: "https://http2.mlstatic.com/D_NQ_NP_884458-MLU69759024127_062023-O.webp",
        stock: "2",
        price: "14900",
    },
    {
        id: 6,
        name: "El Misterio De Salem's Lot",
        author: "Stephen King",
        category: "terror",
        description: "Veinte años atrás, por una apuesta infantil, Ben Mears entró en la casa de los Marsten. Y lo que vio entonces aún recorre sus pesadillas. Ahora, como escritor consagrado, vuelve a Salem's Lot para exorcizar sus fantasmas.",
        image: "https://http2.mlstatic.com/D_NQ_NP_638253-MLA53781047429_022023-O.webp",
        stock: "5",
        price: "12199",
    },
    {
        id: 7,
        name: "Orgullo y Prejuicio",
        author: "Jane Austen",
        category: "romance",
        description: "Narra las aventuras y desventuras amorosas de las hermanas Bennet, centrándose en el personaje de Elizabeth, a través de las cuales la autora nos presenta con comicidad la sociedad de su tiempo y coloca a la mujer en un lugar más notorio que el que le correspondía en su época con la figura de la protagonista.",
        image: "https://http2.mlstatic.com/D_NQ_NP_285915-MLA25342914291_022017-O.webp",
        stock: "10",
        price: "9990",
    },
    {
        id: 8,
        name: "Lo que el viento se llevo",
        author: " Margaret Mitchell",
        category: "romance",
        description: "Rhett Butler, un joven que no quiere luchar en la inminente guerra de Secesión, está enamorado de Scarlett, pero ésta prefiere vengarse de Melanie casándose con su hermano Charles. Sin embargo, cuando la guerra cese, Scarlett habrá enviudado, vivirá en la miseria, y Batler intentará de nuevo seducirla.",
        image: "https://http2.mlstatic.com/D_NQ_NP_762313-MLA51482441670_092022-O.webp",
        stock: "10",
        price: "21000",
    },
    {
        id: 9,
        name: "La Odisea",
        author: "Homero",
        category: "literatura",
        description: "narra la historia del héroe griego Odiseo, Ulises, el viaje de regreso a su reino de Ítaca donde le esperan su esposa Penélope, rodeada de pretendiente, y su hijo Telémaco. Un trayecto de aproximadamente un mes de navegación que se alarga aproximadamente diez años, los mismos que duró la guerra de Troya.",
        image: "https://http2.mlstatic.com/D_NQ_NP_353411-MLA20532748131_122015-O.webp",
        stock: "10",
        price: "7100",
    },
    {
        id: 10,
        name: "Yo antes de ti",
        author: " Jojo Moyes",
        category: "romance",
        description: "Louisa Clark: Una mujer de 26 años que es creativa, talentosa y divertida, pero que se subestima a sí misma y tiene pocas ambiciones. Su vida cambia cuando comienza a trabajar como cuidadora de un hombre paralítico. Con el tiempo, aprende a aprovechar sus capacidades y salir de su zona de comodidad limitada.",
        image: "https://http2.mlstatic.com/D_NQ_NP_906614-MLA31020853380_062019-O.webp",
        stock: "10",
        price: "13000",
    },
    {
        id: 11,
        name: "Don Quijote de la Mancha",
        author: " Miguel de Cervantes",
        category: "literatura",
        description: "cuenta la historia de un hidalgo llamado Alonso Quixano que se vuelve loco al leer demasiados libros de caballería. Quixano decide adoptar el nombre de Don Quijote y salir en busca de aventuras junto a su fiel escudero Sancho Panza.",
        image: "https://http2.mlstatic.com/D_NQ_NP_701311-MLM20510155563_122015-O.webp",
        stock: "10",
        price: "21000",
    },
    {
        id: 12,
        name: "Cementerio de animales",
        author: " Stephen King",
        category: "terror",
        description: "Narra la historia del doctor Louis Creed, que al poco de mudarse con su esposa Rachel y sus dos hijos pequeños desde Boston a un recóndito paraje de Maine, descubre un misterioso cementerio escondido en lo más impenetrable del bosque , a escasa distancia del nuevo hogar familiar.",
        image: "https://http2.mlstatic.com/D_NQ_NP_614318-MLA53781047303_022023-O.webp",
        stock: "10",
        price: "10400",
    }
];


//ctrl + espacio: importa componente de mui